[package]
name = "floresta-node"
version = "0.9.0"
rust-version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true # Floresta/README.md
authors = ["Floresta Developers <contact@getfloresta.org>"]

[dependencies]
# All dependencies MUST be pinned precisely with `X.Y.z`
axum = { workspace = true, optional = true }
bitcoin = { workspace = true }
ethos-bitcoind = { workspace = true }
dns-lookup = { workspace = true }
miniscript = { workspace = true, features = ["std"] }
rcgen = { workspace = true }
rustreexo = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-rustls = { workspace = true }
toml = { workspace = true }
tower-http = { version = "=0.7.0", optional = true, features = ["cors"] }
tracing = { workspace = true }
zmq = { version = "=0.10.0", optional = true, default-features = false }
time = { workspace = true }

# Local dependencies
floresta-chain = { workspace = true, features = ["bitcoinkernel"] }
floresta-compact-filters = { workspace = true, optional = true }
floresta-common = { workspace = true }
floresta-domain = { workspace = true }
floresta-electrum = { workspace = true }
floresta-mempool = { workspace = true }
floresta-watch-only = { workspace = true }
floresta-wire = { workspace = true }
floresta-metrics = { workspace = true, optional = true }

[dev-dependencies]
pretty_assertions = { version = "=1.4.1" }

[target.'cfg(target_env = "gnu")'.dependencies]
libc = { version = "=0.2.186" }

[target.'cfg(target_os = "macos")'.dependencies]
libc = { version = "=0.2.186" }

[features]
compact-filters = ["dep:floresta-compact-filters"]
zmq-server = ["dep:zmq"]
json-rpc = ["dep:axum", "dep:tower-http", "compact-filters"]
default = ["json-rpc"]
metrics = ["dep:floresta-metrics", "floresta-wire/metrics", "floresta-chain/metrics"]

[lints]
workspace = true
